levels_of_descriptions = {
    1: "Archivo Documental",
    2: "Colecciones Fotográficas",
    3: "Fondo Documental",
    4: "Sección Documental",
    5: "Subsección Documental",
    6: "Unidad de Subsección Documental",
    7: "Serie Documental",
    8: "Subserie Documental",
    9: "Unidad Documental",
    10: "Archivo Fotográfico",
    11: "Fondo Fotográfico",
    12: "Sección Fotográfica",
    13: "Reportaje Fotográfico",
    14: "Unidad Fotográfica",
    27: "Sección de la Colección Fotográfica",
    29: "Unidad Fotográfica de la Colección",
    30: "Colección Fotográfica",
    32: "Archivo Gráfico",
    33: "Fondo Gráfico",
    34: "Sección Gráfica",
    35: "Unidad Gráfica",
    37: "Subfondo Documental",
    38: "Fonoteca",
    39: "Fondo Sonoro",
    40: "Sección Sonora",
    41: "Unidad Sonora",
    42: "Videoteca",
    43: "Sección Audiovisual",
    44: "Unidad Audiovisual",
    45: "Fondo Audiovisual",
    46: "Fondos de Procedencia Externa",
    47: "Capitán Vigueras",
    48: "Fondo de Procedencia Externa",
    49: "Sección del Fondo de Procedencia Externa",
    50: "Unidad Documental del Fondo de Procedencia Externa",
    51: "Serie del Fondo de Procedencia Externa",
    53: "Colecciones Gráficas de Procedencia Externa",
    54: "Colección Gráfica de Procedencia Externa",
    55: "Sección de la Colección Gráfica de Procedencia Ext",
    56: "Unidad Gráfica de la Colección de Procedencia Exte",
    57: "Archivo Oral",
    58: "Fondo Oral",
    59: "Sección Oral",
    60: "Memoria Democrática",
}
